FROM golang:1.25 AS build

RUN apt update && apt install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.32.0
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.6.1
ENV PATH="$PATH:$(go env GOPATH)/bin"

COPY go.mod go.sum /src/
RUN cd /src && go mod download

COPY proto /src/proto
COPY api /src/api
COPY platform /src/platform

RUN cd /src && \
    protoc --go_out=.      --go_opt=paths=source_relative \
           --go-grpc_out=. --go-grpc_opt=paths=source_relative \
           proto/subscriber/subscriber.proto \
           proto/processor/processor.proto

ENV CGO_ENABLED=0
RUN cd /src && go build -o /api api/cmd/app/main.go

FROM scratch

COPY --from=build /api /api

ENTRYPOINT ["/api", "-config", "/config.yaml"]
