// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (owner, repo_name)
VALUES ($1, $2)
RETURNING id, owner, repo_name, created_at
`

type CreateSubscriptionParams struct {
	Owner    string
	RepoName string
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.Owner, arg.RepoName)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.RepoName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM subscriptions
WHERE owner = $1
    AND repo_name = $2
`

type DeleteSubscriptionParams struct {
	Owner    string
	RepoName string
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscription, arg.Owner, arg.RepoName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubscriptions = `-- name: GetSubscriptions :many
SELECT id, owner, repo_name, created_at
FROM subscriptions
ORDER BY id
`

func (q *Queries) GetSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.RepoName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsRepoInfo = `-- name: GetSubscriptionsRepoInfo :many
SELECT owner, repo_name
FROM subscriptions
ORDER BY id
`

type GetSubscriptionsRepoInfoRow struct {
	Owner    string
	RepoName string
}

func (q *Queries) GetSubscriptionsRepoInfo(ctx context.Context) ([]GetSubscriptionsRepoInfoRow, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsRepoInfo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSubscriptionsRepoInfoRow{}
	for rows.Next() {
		var i GetSubscriptionsRepoInfoRow
		if err := rows.Scan(&i.Owner, &i.RepoName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
