FROM golang:1.25-alpine AS builder

WORKDIR /src

RUN apk add --no-cache ca-certificates git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/subscriber ./subscriber/cmd

FROM alpine:3.20

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /out/subscriber /app/bin/subscriber
COPY --from=builder /src/subscriber/migrations /app/migrations

ENTRYPOINT ["/app/bin/subscriber", "-config", "/config.yaml"]
